sudo: required
services:
  - docker

before_install:
  - docker build -t lorenz90/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run lorenz90/react-test npm test -- --coverage

after_succes:
  - docker build -t lorenz90/multi-client ./client
  - docker build -t lorenz90/multi-nginx ./nginx
  - docker build -t lorenz90/multi-server ./server
  - docker build -t lorenz90/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push lorenz90/multi-client
  - docker push lorenz90/multi-nginx
  - docker push lorenz90/multi-server
  - docker push lorenz90/multi-worker

